// tests/unit/round-trip-matrix.test.js
// M2.1 round-trip matrix — self-check block.
//
// Two assertions:
//   1. sizeFleet() runs without throwing for both 9.0 and 9.1 — a basic
//      structural sanity check (incoherent enriched values throw here).
//   2. Every major factory's output key appears in the serialised tree —
//      ensures the kitchen-sink builder exercised every reachable factory.
//
// Key list uses REAL property names confirmed against engine.js:
//   - federationConfig   (createFleetFederationConfig)
//   - localManager       (createFederationLocalManager  — singular, not localManagers)
//   - tier1              (createFederationTier1          — singular, not tier1s)
//   - adConfig           (createFleetAdConfig)
//   - backupConfig       (createFleetBackupConfig)
//   - installerConfig    (createFleetInstallerConfig)
//   - namingConfig       (createFleetNamingConfig)
//   - reportMetadata     (createFleetReportMetadata)
//   - supervisorConfig   (createClusterSupervisorConfig)
//   - deployment         (createSupervisorDeployment — nested under supervisorConfig)
//   - az2Networks        (createClusterAz2Networks)
//   - az2HostOverlay     (createClusterAz2HostOverlay)
//   - vsanCompute        (createClusterVsanCompute)
//   - edgeCluster        (createEdgeCluster)
//   - nodes              (createEdgeNode[] inside edgeCluster.nodes)
//   - t0Gateways         (newT0Gateway[] — array, singular key present in serialised JSON)
//   - hostOverrides      (createHostIpOverride[] — array)
//   - portgroups         (createClusterPortgroups — object under networks)
//   - nsxHostOverlay     (createClusterNsxHostOverlay — under networks)
//   - advanced           (baseClusterAdvanced)
//   - witnessConfig      (createWitnessConfig — on instance)
//   - globalManager      (federation global manager with nodes)

import { describe, it, expect } from "vitest";
import VcfEngine from "../../engine.js";
import { buildKitchenSinkFleet } from "../helpers/kitchen-sink-fleet.js";
import { stampSentinels } from "../helpers/sentinel-walk.js";

describe("kitchen-sink fleet — self check", () => {
  it("sizes without throwing on 9.0 and 9.1", () => {
    for (const vcfVersion of ["9.0", "9.1"]) {
      const fleet = buildKitchenSinkFleet({ vcfVersion });
      expect(() => VcfEngine.sizeFleet(fleet)).not.toThrow();
    }
  });

  it("exercises every exported create*/new* factory (output key reachable)", () => {
    const fleet = buildKitchenSinkFleet({ vcfVersion: "9.1" });
    const json = JSON.stringify(fleet);

    const expectedKeys = [
      // Fleet-level factory outputs
      "federationConfig",
      "localManager",    // singular — createFederationLocalManager
      "tier1",           // singular — createFederationTier1
      "globalManager",   // federation GM with nodes
      "adConfig",
      "backupConfig",
      "installerConfig",
      "namingConfig",
      "reportMetadata",
      "witnessConfig",   // createWitnessConfig on instance

      // Cluster-level factory outputs (all wired by newCluster / enrichCluster)
      "supervisorConfig",
      "deployment",      // createSupervisorDeployment under supervisorConfig
      "az2Networks",
      "az2HostOverlay",
      "vsanCompute",
      "edgeCluster",
      "nodes",           // createEdgeNode[] inside edgeCluster
      "t0Gateways",
      "hostOverrides",
      "portgroups",      // createClusterPortgroups under networks
      "nsxHostOverlay",  // createClusterNsxHostOverlay under networks
      "advanced",
    ];

    for (const key of expectedKeys) {
      expect(json, `expected "${key}" present in kitchen-sink tree`).toContain(`"${key}"`);
    }
  });
});

// ─── Leaf names that are STRUCTURAL (discriminators / generated ids) ──────────
// These are NOT free-form user data — they drive engine branching or are
// regenerated by the engine on migrate. Stamping them with garbage would cause
// false failures (migrate LOGIC breaks, not a whitelist gap). Each is classified
// STRUCTURAL_IGNORE for Task 6.
//
//   type             — domain discriminator ("mgmt" / "workload"). migrateFleet
//                      uses `d.type === "mgmt"` to find the mgmt domain and
//                      resolve componentsClusterId / defaultRole / wldStack;
//                      stamping it breaks the entire domain-mapper logic,
//                      producing many cascade failures.
//   id               — entity ids (fleet, instance, domain, cluster, t0, etc.).
//                      migrateFleet uses `d.id`, `c.id` for cross-reference
//                      lookups (firstWldCluByDomId, mgmtFirstCluId). The engine
//                      also reasserts `fleet.id` via `fleet.id || "fleet-"+localId()`.
//   key              — wldStack / infraStack entry keys. Regenerated via
//                      `e.key || localId()` in the wldStack mapper; a missing-
//                      or-new key is expected structural behaviour, not a gap.
//   version          — migration version discriminator ("vcf-sizer-v9" etc.).
//                      migrateFleet branches on this to select the migration
//                      path: stamping it to "rt::version" triggers the v3→v5
//                      migrator, which completely restructures instances/domains
//                      and causes 731 cascade failures. Must stay a valid value.
//   ssoMode          — SSO mode enum validated against SSO_MODES dict.
//                      An invalid stamped value is inferred away by
//                      `inferSsoMode()`, which looks like a round-trip drop but
//                      is really an enum-validation replacement.
//   principalStorage — Storage type enum: ["vSAN-ESA","vSAN-OSA","VMFS on
//                      Fibre Channel (FC)","NFSv3"]. In migrateV5ToV6,
//                      `PRINCIPAL_STORAGE_OPTIONS.includes(existing) ? existing
//                      : "vSAN-ESA"` resets any unknown value to the default.
//   placement        — Domain placement discriminator ("local" / "stretched").
//                      The domain mapper recomputes `localSiteId` entirely from
//                      this field; stamping it breaks the siteId resolution chain.
//   localSiteId      — Recomputed by the domain mapper as a cross-reference to
//                      inst.siteIds[]. Since both are stamped independently, the
//                      include-check always fails and localSiteId resolves to
//                      siteIds[0] regardless. Not free-form user data.
const STRUCTURAL_SKIP = new Set([
  "type",
  "id",
  "key",
  "version",
  "ssoMode",
  "principalStorage",
  "placement",
  "localSiteId",
]);

// ─── Known whitelist gaps in migrateFleet (genuine engine bugs) ───────────────
// Each path below is a value-bearing user field that migrateFleet silently
// drops or does not preserve. Do NOT edit engine.js to fix these — they are
// tracked as follow-up engine bugs. The test filters them out so the suite
// stays green while making the gaps visible.
//
// (empty — no gaps found as of this writing)
const KNOWN_MIGRATE_GAPS = [
  // BUG: <path>  — <explanation>   ← add entries here if gaps are found
];

// Helper: resolve a dot-delimited path in an object, supporting integer
// array indices as well as string keys.
function getPath(obj, path) {
  return path.split(".").reduce((o, k) => (o == null ? o : o[k]), obj);
}

describe("round-trip matrix — JSON save/load completeness", () => {
  it("every value-bearing field survives JSON.stringify -> migrateFleet", () => {
    const base = buildKitchenSinkFleet({ vcfVersion: "9.1" });
    const { stamped, sentinels } = stampSentinels(base, { skipLeafNames: STRUCTURAL_SKIP });
    const rebuilt = VcfEngine.migrateFleet(JSON.parse(JSON.stringify(stamped)));

    // Filter out known whitelist gaps so the suite stays green while
    // keeping the bugs visible in KNOWN_MIGRATE_GAPS above.
    const knownGapSet = new Set(KNOWN_MIGRATE_GAPS);

    const missing = [];
    for (const [path, expected] of Object.entries(sentinels)) {
      if (knownGapSet.has(path)) continue;
      if (getPath(rebuilt, path) !== expected) {
        missing.push(
          `${path} (expected ${JSON.stringify(expected)}, got ${JSON.stringify(getPath(rebuilt, path))})`
        );
      }
    }
    expect(
      missing,
      `JSON round-trip dropped/changed ${missing.length} field(s):\n${missing.join("\n")}`
    ).toEqual([]);
  });
});
